<a href="https://colab.research.google.com/github/KiranSinha872/data_science_june/blob/main/NUMPY01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

# np.array() -> Creates a NumPy array from a Python list
a = np.array([1, 2, 3])
print(a)

# np.array() -> Creates a 2D array (matrix) from nested lists
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)


# np.zeros() -> Creates an array filled with 0s
c = np.zeros(5)      # 1D array of 5 zeros
print(c)

# np.zeros() -> Creates a 2D array of zeros
d = np.zeros((2, 3)) # 2 rows, 3 columns
print(d)


# np.ones() -> Creates an array filled with 1s
e = np.ones(3)
print(e)


# np.empty() -> Creates an array without initializing values
# Values are random garbage data already present in memory
f = np.empty((2, 2))
print(f)


# np.full() -> Creates an array filled with a specified value
g = np.full((2, 3), 9)
print(g)


# np.random.randint() -> Generates random integers
# Syntax: randint(start, end, size)
# Generates 19 random integers between 1 and 99
miii = np.random.randint(1, 100, 19)
print(miii)


# np.arange() -> Creates values with a fixed step size
# Syntax: arange(start, stop, step)
h = np.arange(1, 10, 2)  # 1, 3, 5, 7, 9
print(h)


# np.linspace() -> Creates evenly spaced numbers
# Syntax: linspace(start, stop, number_of_values)
i = np.linspace(0, 10, 5)
print(i)  # [0.  2.5  5.  7.5 10.]

[1 2 3]
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[4.57333540e-315 0.00000000e+000]
 [1.19831365e-304 4.02978715e-318]]
[[9 9 9]
 [9 9 9]]
[76 34 77 87 78 46 76 40 76 48  6 97 65 76  7 50 85  2 14]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]


| Function              | Purpose                                  |
| --------------------- | ---------------------------------------- |
| `np.array()`          | Create array from list                   |
| `np.zeros()`          | Array filled with 0                      |
| `np.ones()`           | Array filled with 1                      |
| `np.empty()`          | Uninitialized array                      |
| `np.full()`           | Array filled with a custom value         |
| `np.random.randint()` | Random integers                          |
| `np.arange()`         | Numbers with fixed step size             |
| `np.linspace()`       | Evenly spaced numbers between two limits |


In [3]:
# ARRAY INSPECTION & OPERATIONS

import numpy as np

# Creating a 2D NumPy array (2 rows × 3 columns)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# .shape -> Returns dimensions of the array (rows, columns)
shape = arr.shape
print(shape)   # (2, 3)


# Creating a 1D array
m = np.array([1, 2, 3])

# .size -> Returns total number of elements in the array
print(m.size)   # 3

# .dtype -> Returns data type of array elements
print(m.dtype)  # int64 (may vary by system)


# ---------------- BROADCASTING ----------------

n = np.array([1, 2, 3, 9, 6, 7, 8, 0])

# Broadcasting:
# Adds 10 to every element of the array automatically
print(n + 10)


# ---------------- TRANSPOSE ----------------

# .T -> Transposes rows into columns and columns into rows
print(arr.T)


# ---------------- CONCATENATE ----------------

new = np.array([
    [1, 2, 3],
    [9, 8, 7]
])

# np.concatenate()
# Combines arrays along a specified axis
# axis=0 -> stack rows
# axis=1 -> join columns

combined = np.concatenate((arr, new), axis=1)
print(combined)


# ---------------- WHERE ----------------

# np.where(condition)
# Returns indices where the condition is True

indices = np.where(n > 3)
print(indices)

# np.where(condition, value_if_true, value_if_false)
# Example:
result = np.where(n > 3, 100, n)
print(result)


# ---------------- SORT ----------------

# np.sort() returns a sorted COPY of the array
sorted_n = np.sort(n)
print(sorted_n)

# Original array remains unchanged
print(n)


# ---------------- AGGREGATE FUNCTIONS ----------------

# .sum() -> Sum of all elements
print(n.sum())

# .mean() -> Average of all elements
print(n.mean())

# .max() -> Largest value in the array
print(n.max())


# ---------------- UNIQUE VALUES ----------------

# np.unique() -> Returns unique elements in sorted order
k = np.unique(n)
print(k)


# ---------------- MATRIX MULTIPLICATION ----------------

l = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

o = np.array([
    [1, 2],
    [4, 5],
    [1, 2]
])

# np.matmul() -> Matrix multiplication
# Shape: (2×3) × (3×2) = (2×2)
mul = np.matmul(l, o)
print(mul)

# Alternative:
# mul = l @ o


# ---------------- RANDOM NUMBERS ----------------

# np.random.randint(start, end)
# Generates ONE random integer between start and end-1
random_num = np.random.randint(1, 10)
print(random_num)

# np.random.randint(start, end, size)
# Generates an array of random integers
new_random = np.random.randint(1, 10, 5)
print(new_random)

(2, 3)
3
int64
[11 12 13 19 16 17 18 10]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 1 2 3]
 [4 5 6 9 8 7]]
(array([3, 4, 5, 6]),)
[  1   2   3 100 100 100 100   0]
[0 1 2 3 6 7 8 9]
[1 2 3 9 6 7 8 0]
36
4.5
9
[0 1 2 3 6 7 8 9]
[[12 18]
 [30 45]]
5
[6 6 1 9 4]


| Function              | Use                               |
| --------------------- | --------------------------------- |
| `shape`               | Dimensions of array               |
| `size`                | Total elements                    |
| `dtype`               | Data type                         |
| `+ number`            | Broadcasting                      |
| `.T`                  | Transpose                         |
| `np.concatenate()`    | Join arrays                       |
| `np.where()`          | Conditional selection/replacement |
| `np.sort()`           | Sort array                        |
| `.sum()`              | Sum of elements                   |
| `.mean()`             | Average value                     |
| `.max()`              | Maximum value                     |
| `np.unique()`         | Unique elements                   |
| `np.matmul()` / `@`   | Matrix multiplication             |
| `np.random.randint()` | Random integers                   |


In [4]:
import numpy as np

# Create array 1-20
arr = np.arange(1, 21)
print(arr)

# Reshape to 4x5
arr = arr.reshape(4, 5)
print(arr)

# Find shape
print("Shape:", arr.shape)

# Find sum
print("Sum:", arr.sum())

# Find mean
print("Mean:", arr.mean())

# Replace values >10 with 100 using where
new_arr = np.where(arr > 10, 100, arr)
print(new_arr)

# Find unique values
print("Unique values:", np.unique(arr))

# Transpose matrix
print("Transpose:")
print(arr.T)

# Generate random 3x3 matrix
random_matrix = np.random.randint(1, 100, (3, 3))
print("Random Matrix:")
print(random_matrix)

# Multiply matrix by 2
print("Matrix * 2:")
print(random_matrix * 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (4, 5)
Sum: 210
Mean: 10.5
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [100 100 100 100 100]
 [100 100 100 100 100]]
Unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Transpose:
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
Random Matrix:
[[54 82 20]
 [52 11 15]
 [ 8 56  4]]
Matrix * 2:
[[108 164  40]
 [104  22  30]
 [ 16 112   8]]
